### ISSUE TITLE
Manage milestones

### ISSUE THREAD

**Issue by webmozart** [carsonbot/carsonbot#10]
This is more an idea than a feature request:

The bot could manage the milestones of the project automatically. Whenever a new tag is released (e.g. 2.7.2), a milestone for the next version is created (e.g. 2.7.3). Likewise, when a new minor version is released (e.g. 2.7.0), a new milestone for the next version should be created (e.g. 2.8.0).

This feature really becomes useful when we set PR milestones automatically based on their base branch. For example, a PR based on branch 2.7 would be assigned to the latest 2.7 milestone (here: 2.7.3).

When a version is released and the corresponding milestone still contains open tickets, these tickets should be moved to the next milestone (e.g. 2.7.2 -> 2.7.3).

As a result, we could work on next versions more efficiently by checking which PRs and issues are assigned to particular milestones before doing a release.

Not sure if the work in this is warranted, but I think it could be useful. :)

**Comment by stof** [comment]
given that we regularly switch the branch on merge, this could create weird things where PRs in the 2.7.2 milestone are merged into the next 2.3 version

**Comment by webmozart** [comment]
@stof True, but do you think that's a big deal?

**Comment by stof** [comment]
Well, what would be the benefit of these milestones then ?

**Comment by webmozart** [comment]
The benefit is to chunk down the PRs into more digestible parts. You are right that this view is not perfect, because a ticket that should belong to some 2.3.x milestone may actually be targeted at some 2.7.x milestone. But:

* I don't think we need perfect. PRs eventually get merged anyway (or not).
* Whether or not the branch/milestone is correct should [turn up during review](https://github.com/webmozart/symfony-docs/blob/reviews/contributing/community/reviews.rst#the-pull-request-review-process). The milestone can then be corrected from the UI. We could actually support milestone changes similarly to status changes.

**Comment by stof** [comment]
@webmozart do we need a 2.7.3 milestone then ? I think milestones per version (2.3, 2.7, 2.8) would be enough to see what is pending for each version.

**Comment by webmozart** [comment]
Maybe. Usually, a milestone is something that can be reached and completed. If we have a 2.3 milestone, that milestone is never complete until we don't maintain 2.3 anymore.

But maybe that solution is sufficient :) It sure is simpler.

**Comment by stof** [comment]
well, if the milestone is only used for triaging, this is enough.

**Comment by xabbuh** [comment]
👍 on this now that we use milestones for triaging

**Comment by Nyholm** [comment]
This is fixed in #87
