### ISSUE TITLE
Close PRs when they are rebased when merging with GH

### ISSUE THREAD

**Issue by stof** [carsonbot/carsonbot#16]
The commit message generated by GH ensures that github will close the PR automatically, but this only happens when the merge commit reaches the default branch of the repo (2.8 currently).
Given that it sometimes takes more than 1 week to get 2.3 changes merged into 2.8, there are 2 cases currently:
- either the merger has to come and close it manually
- or the PR stays open while it is already merged, opening the door for mistakes.

It would be great if the bot could look for pushed commits in development branches (i.e. ``master`` and ``2.*``, but not feature branches created in the main repo by a core team member by mistake) and close PRs when it finds such a commit (GH has predefined commit messages which are easy to catch to identify such cases).

An extra feature could be to post a comment explaining why the PR appears as closed rather than merged (similar to what the documentation team is doing manually currently).

**Comment by sstok** [comment]
You can also inform the GitHub API (by using GH) to close the PR, thats what we are doing in Gush.
And would actually also work for repo's like the FOSUserBundle and FriendsOfPHP (which don't use carsonbot).

**Comment by keradus** [comment]
If I remember it right once it works for GH.

One way or another I think it should be done by GH too.

**Comment by stof** [comment]
this should indeed be fixed in GH instead

**Comment by keradus** [comment]
Then no work for carsonbot here? Maybe you could move the issue to gh?

**Comment by HeahDude** [comment]
Is there any update here? Is it still an issue?
