### ISSUE TITLE
The webhook should take profit of all data sent in the payload

### ISSUE THREAD

**Issue by stof** [carsonbot/carsonbot#19]
For each action happening on an issue, the issue listener will perform API calls to retrieve the labels of an issue.
However, this is a useless call: the payload being submitted by github to the webhook already contains all informations about the issue as retrieved by the issue API, and this include the list of labels applied on it: https://developer.github.com/v3/activity/events/types/#issuecommentevent

We could use this information instead of making another call

**Comment by HeahDude** [comment]
This can be closed since data are now passed through the event with #33.
