### ISSUE TITLE
use library for issue communication

### ISSUE THREAD

**Issue by digitalkaoz** [carsonbot/carsonbot#2]
you could use https://github.com/digitalkaoz/issues or even https://github.com/digitalkaoz/IssuesBundle for interacting with github issues :)

**Comment by weaverryan** [comment]
@digitalkaoz ah, thanks for showing me! I didn't know about this. If we continue dev on this library, I'll look into using it :)

**Comment by webmozart** [comment]
What's the benefit over the KNP GitHub API in a nutshell?

**Comment by digitalkaoz** [comment]
it abstracts github (also jira gitlab bitbucket) and api interaction into a
common interfaced object world.

Bernhard Schussek <notifications@github.com> schrieb am Do., 16. Juli 2015
17:14:

**Comment by webmozart** [comment]
Oh cool :) I don't think that this abstraction brings any benefit though, since we primarily focus on Symfony and GitHub (for now).

If Carson ever becomes some sort of SAAS, this will be interesting.

**Comment by Nyholm** [comment]
This issue can be closed
