### ISSUE TITLE
Allow enterprise github installations to be used

### ISSUE THREAD

**Issue by HexTitan** [carsonbot/carsonbot#21]
Currently, github.com is hard-coded. While Carson Bot is intended to be used on Symfony, I can see this being very useful for other people, and businesses may have an [enterprise github installation.](https://enterprise.github.com/home) My suggestion be to remove the hard-coded values and provide a configuration option for these enterprise installations to point to the correct API endpoints.

**Comment by webmozart** [comment]
Thanks for your suggestion! :) Our current focus is obviously to make things working for Symfony, but if you want to provide a PR for this feel free to submit one. Cheers!

**Comment by nicolas-grekas** [comment]
Shall be closed IMHO.
