### ISSUE TITLE
Create a bundle to allow third party app to use the carsonbot

### ISSUE THREAD

**Issue by Ener-Getick** [carsonbot/carsonbot#24]
What do you think about creating a ``CarsonbotBundle`` to allow people to use it in a regular app ?

**Comment by WouterJ** [comment]
:-1: CarsonBot as a feature in an application is not usefull, carson bot is an app on its own.

You can clone this repository locally, create a github account, use it in the code and run it on a web server and set up the GitHub events to trigger carson bot.

**Comment by Ener-Getick** [comment]
Well you're right, carsonbot as a bundle is probably not really useful in the current state as it is not customizable...
