### ISSUE TITLE
Set status to reviewed when a core-team member votes

### ISSUE THREAD

**Issue by nicolas-grekas** [carsonbot/carsonbot#25]

**Comment by HeahDude** [comment]
There should be a kind of "rule" then to keep the regex simple since votes can be made on minor comments.

**Comment by HeahDude** [comment]
Same rule should apply to #7.

So 1 vote gets the status "reviewed" and two gets it "ready. What do you think?

**Comment by weaverryan** [comment]
Makes sense to me - we could try it first on the docs (a safer sandbox for testing workflows)

**Comment by stof** [comment]
this should then also handle the case of `-1` votes being a veto

**Comment by nicolas-grekas** [comment]
Note that explicit -1 should veto, but review refusal should not be considered as veto

**Comment by stof** [comment]
yeah, requesting changes on a review moves back to `Needs work` (there are already PRs for that), but does not block the later approval
