### ISSUE TITLE
Handle setting the status while opening the PR

### ISSUE THREAD

**Issue by nicolas-grekas** [carsonbot/carsonbot#26]
The bot adds "Status: needs review" even if I add "Status: needs work" in the PR description

**Comment by HeahDude** [comment]
I think Carson should not be used this way, statuses are meant to be changed by comment not by opening where the listener parse the title and the filled template. There was an attempt to deal with WIP in #39 but it's closed.

What I suggest instead is that putting `[WIP]` at the beginning of the title just prevents defaulting on "needs review" label.

Then a comment can define one of both if needed.

**Comment by nicolas-grekas** [comment]
I don't like using WIP in the title at all because then, the corresponding thread in my email inbox always starts with WIP even if it's not WIP anymore.
I still think this feature request is the proper way to deal with that instead.

**Comment by xabbuh** [comment]
I think I agree with @nicolas-grekas here. Imo the PR description is not very different from a subsequent comment in the context of setting the status labels.

**Comment by chalasr** [comment]
Should be solved by https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by Nyholm** [comment]
I think this can be closed.
