### ISSUE TITLE
Autolabel pull requests after they are created

### ISSUE THREAD

**Issue by javiereguiluz** [carsonbot/carsonbot#27]
In #8 @webmozart proposed a way to label PRs after scanning the files modified by the PR. I propose now an alternative way to auto-label PRs which would be easier to implement and which would help us in most of the cases.

If a user submits the following:

```
[Form] Allow usage of immutable collection

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | unsure
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |
```

1. We should consider the first bracketed prefix (`[Form]` in this case) as the name of the component/bundle/bridge.
2. We should consider the `Bug fix?` and `New feature?` answers to add the `Bug` and/or `Feature` labels.

**Comment by webmozart** [comment]
I like 2! :)

About 1, I would still prefer to base our labels on the files. [Apparently the changed files are easy to get](https://developer.github.com/v3/pulls/#list-pull-requests-files), and we only need to match their paths against a quite basic regular expression to extract the component/bundle/bridge name. This is certainly more error-proof than relying on user-provided title prefixes, which are often enough missing (and could even be omitted or added automatically/corrected by the same tool!).

**Comment by sstok** [comment]
:+1: I wonder if something can be done for the issues also? I actually thought about that, but issues are more tricky as something can be seen as bug to one while it's actually a wrong usage or misunderstood logic.

**Comment by weaverryan** [comment]
I like it! Please, someone do it - we need the automation!

**Comment by HeahDude** [comment]
We could even use the `Tests pass?` question to do something like `$status = $testsPass ? Status::NEEDS_REVIEW : STATUS::NEEDS_WORK`. What do you think?

**Comment by HeahDude** [comment]
Why not parse the fixed tickets to add the issues a "hasPR" label?

**Comment by weaverryan** [comment]
See #34 

The "Tests pass" is interesting, but honestly, it would be more interesting if Carson actually looked at the TravisCI build. But also, *sometimes* there are failures that are unrelated to the PR, and I don't want to cause extra noise. When Carson does something, it should be 99.9% accurate - to avoid the "bot" becoming annoying.

**Comment by javiereguiluz** [comment]
@weaverryan I see that people are asking for more and more features. I think we should ignore them ... temporarily. Let's merge something small but useful ... and once it's working, let's build on top of that the new features suggested by friends like @HeahDude :)

**Comment by weaverryan** [comment]
Yep, I'm closing this, because I *did* just merge in the PR that fixes this :)

**Comment by HeahDude** [comment]
Ok then I'll open an issue later for some other suggestions :) Thanks guys!
