### ISSUE TITLE
Add "On Hold" status for documenation

### ISSUE THREAD

**Issue by weaverryan** [carsonbot/carsonbot#35]
This status is used currently when an issue is waiting for the up-stream code to be merged.

**Comment by HeahDude** [comment]
This should go along with "Ready", don't you think?

**Comment by WouterJ** [comment]
I think "Ready" should be removed and "Status: Reviewed" should be used instead. I think these are equal.

**Comment by HeahDude** [comment]
A PR could be "reviewed" and "on hold", so "ready" would be missing opposite here.

Currently, "ready" in symfony core should be private and maybe implemented in a listener when there is to ":+1:"  from maintainers. And this could go for the docs but with "finished" instead of "ready".

**Comment by weaverryan** [comment]
#25 is indeed similar to this idea about "ready" :)

**Comment by HeahDude** [comment]
Ah, I was not aware of #25 :) This is not the same as "reviewed" IMHO, it's independent from the review (that can be from anyone), also sometimes a core member change the status to reviewed with a ":+1:" but there is still not two of them.
I think "Ready" and "Finished" should be used for private hooks.

**Comment by WouterJ** [comment]
Please note that one :+1: is enough to call it ready, as the merger will have the other +1.

**Comment by Nyholm** [comment]
Is this something we still want to implement?

**Comment by Nyholm** [comment]
So, I think I can solve this. 

On symfony-docs: 
- I see if the PR body contains a link to a symfony/symfony PR. If that PR is open, then I add the "On hold". 
- I also save a reference to the docs PR in the database

On symfony: 
- On merge, I ask github for the PR timeline
- I look a the time line for a "cross-referenced" event. If the related issue matches something I have in the databse, then I remove the "On hold" label. 

--------

Do we want this? How useful is the "on hold" label?

**Comment by Nyholm** [comment]
Im leaning towards closing this

**Comment by wouterj** [comment]
Oh sorry for not responding here.

This is a process I'm currently doing manually. We all tag PRs related to unmerged features as "Waiting Code Merge" and go over the list of WCM PRs every once in a while (it's only really needed to do it once every 6 months).

So this is definitely not a must have and given the complexity required to automate, I agree that closing is the best thing for now.

**Comment by Nyholm** [comment]
Okey. Let's close for now and see if the requirement changes in the future.
