### ISSUE TITLE
Change Confirmed/Unconfirmed labels into statuses

### ISSUE THREAD

**Issue by chalasr** [carsonbot/carsonbot#43]
To me, the "Confirmed" and "Unconfirmed" labels represent the two possible statuses of a bug, not a standalone kind of issue. 

That's why I propose to change them into "Status: Confirmed" and "Status: Unconfirmed", assignable **only on "Bug" labelled issues**.

More, I would like to see "Status: Unconfirmed" automatically assigned at the same time of the "Bug" one when creating an issue and don't see the "Status : Reviewed/Needs review" labels anymore for these very same issues (Bug).
For bugs we are talking about confirmation, not review, labels are already in place. 
For proposals/feature requests, talking of review doesn't feel adapted but we could still use it (for all issues that aren't bug reports).

WDYT?

**Comment by weaverryan** [comment]
Let me summarize:

* For bugs, stop auto-assigning "Status: Needs Review" and instead auto-assign "Status: Unconfirmed"

* Introduce 2 new statuses (only allowed on issues with a "Bug" label): "Unconfirmed" and "Confirmed"

If this is accurate, it makes good sense to me. Let's see a PR!

**Comment by chalasr** [comment]
See https://github.com/carsonbot/carsonbot/pull/45#issuecomment-267759131
