### ISSUE TITLE
Limit author's permissions to change status

### ISSUE THREAD

**Issue by webmozart** [carsonbot/carsonbot#5]
Authors of a PR/issue should be prevented to change the status of their PR/issue to anything else but "Needs Review". So they cannot do:
- "Needs Review" -> "Reviewed"

However, they can do:
- "Needs Work" -> "Needs Review"

**Comment by stof** [comment]
should they also be able to change it to ``Needs work`` ?

**Comment by webmozart** [comment]
@stof yes, makes sense!
