### ISSUE TITLE
Review summaries are ignored

### ISSUE THREAD

**Issue by ogizanagi** [carsonbot/carsonbot#50]
It seems that the review summaries introduced by Github in ["A whole new Github universe: Code better with reviews"](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features#code-better-with-reviews) are ignored by carsonbot.

See https://github.com/symfony/symfony/pull/20418#pullrequestreview-7846023 for instance.

**Comment by xabbuh** [comment]
Note that we will have to wait for GitHub to expose review comments one way or the other through their API so that the KnpLabs library can be updated if needed.

**Comment by yceruto** [comment]
@ogizanagi : In the meantime, could you change the status to reviewed using the traditional comment? :smile: Thank you!

**Comment by ogizanagi** [comment]
@yceruto : Now that the issue is reported, for sure! 😅
