### ISSUE TITLE
Autolabel issues

### ISSUE THREAD

**Issue by javiereguiluz** [carsonbot/carsonbot#53]
Today Symfony added a template to issues similar to the PR template. See a random example here of the template in action: https://github.com/symfony/symfony/issues/20901

So we can now autolabel issues as "Bug", "Feature", etc.

**Comment by xabbuh** [comment]
I think the issue you are referring to is symfony/symfony#20295.

**Comment by javiereguiluz** [comment]
@xabbuh in fact I linked to a random issue that uses the new template ... but your issue may be a better reference because it's the original PR that added the template 👍

**Comment by javiereguiluz** [comment]
Closing because we no longer use a strict template for issues. We now use GitHub templates (https://blog.github.com/2016-02-17-issue-and-pull-request-templates/, https://blog.github.com/2018-05-02-issue-template-improvements/).
