### ISSUE TITLE
Are you fine? (PRs not always labeled)

### ISSUE THREAD

**Issue by ogizanagi** [carsonbot/carsonbot#54]
Dear Carsonbot,

Are you okay, dude?

I wrote you some issues and PRs. But nothing seems to move you. 
Did I make something wrong?

Or maybe are you in troubles my friend? We can talk about it. I'm pretty sure everyone here would be glad to help you.

Best regards and warm wishes,

Ogi. 🐱 

---

I've noticed more and more PRs/~~issues~~ misses their labels lately, despite the proper format used in titles. Sometimes it doesn't work for labelling from titles, but works for community reviews. See https://github.com/symfony/symfony/pull/21424 for instance.
Is this only about some Github services outages, Carsonbot crashes or anything else?

**Comment by sstok** [comment]
![4221396001_4675520050001_4675517055001-vs](https://cloud.githubusercontent.com/assets/904790/22364384/7120ab7a-e471-11e6-8bf3-8bf73b3884c7.jpg)

Maybe he got replaced by Ben Carson 😆

**Comment by wouterj** [comment]
Afaik, most of the things Carson does only work for PRs. The PR format in issues is quite new and seems to be not yet integrated in carson.

**Comment by chalasr** [comment]
Looks like carson resurrected (see last PRs properly labelled).

**Comment by ogizanagi** [comment]
@chalasr : It only happens from time to time. I noticed more issues around 6pm but it may not be relevant.

See last PRs on `symfony/symfony`:

<img width="898" alt="screenshot 2017-01-28 a 19 56 44" src="https://cloud.githubusercontent.com/assets/2211145/22399034/f11c89ca-e593-11e6-88b6-395211947850.PNG">

The latest ones are not labeled. Even if a third one was some minutes ago.
