### ISSUE TITLE
Add state "Needs Decision"

### ISSUE THREAD

**Issue by webmozart** [carsonbot/carsonbot#6]
The state "Needs Decision" should be supported. This state informs deciders that they should look and vote about a PR.

Only core team members should be allowed to set this status.

**Comment by stof** [comment]
should it be automated then ? core team members are allowed to manage labels in the UI

**Comment by weaverryan** [comment]
What status should a new feature issue request be set to? For example, https://github.com/symfony/symfony/issues/15296. In some sense, the goal of the issue is to gain a yay/nay that it is a good idea to work on. What status should it have - Needs Review? And then assuming it gets a "+1" to do it, then what status?

**Comment by webmozart** [comment]
Hard to say. On one hand, I'd say that we shouldn't include feature issues in our process since bug reports and PRs need much more attention/are much more important. On the other hand, you're right that without a general yay/nay, there's not a lot of motivation for community members to implement a feature.

A solution could be to assign "Needs Decision" to new feature request. That status is targeted at the symfony/deciders crowd.

In any case, I think the priority of feature issues is super low compared to the rest of our todo list.

**Comment by weaverryan** [comment]
Let's run with "Needs Decision" when that's ready and see how it works

**Comment by HeahDude** [comment]
I don't think this adds any value to "needs review", and would need an "accepted" counter part to really be efficient IMHO.

**Comment by weaverryan** [comment]
We're kind of using "Ready" on core right now, which is a manual label. Let's keep using that and not involve Carson.
