### ISSUE TITLE
Auto ask for a review

### ISSUE THREAD

**Issue by lyrixx** [carsonbot/carsonbot#61]
Hello.

I think I could be nice to auto ask a review based on the modified files.

For example, if someone modify the workflow component, carson will add me as a reviewer.

Of course, it will be optin for those who want this system because I would be very nice for me (low activity on "my" component) and a notification storm for other (like fab / niko / stof).

WDYT?

**Comment by javiereguiluz** [comment]
In the past this was complicated and you had to use dedicated tools such as https://github.com/facebook/mention-bot

But a few days ago GitHub enabled this feature. You now see the "suggested reviewers" for any PR:

![github-suggestions](https://cloud.githubusercontent.com/assets/73419/25232115/9b1ce3e4-25da-11e7-9ff7-a01b38836d7b.png)

**Comment by lyrixx** [comment]
Yes, that's exactly what I want to leverage.

**Comment by HeahDude** [comment]
@javiereguiluz Suggestions does not trigger asking for a review though, I use this feature a lot as it sends a mail (notification) in such case, which can be filter thanks to the corresponding cc `review_requested@noreply.github.com`.

**Comment by javiereguiluz** [comment]
In theory this looks like a nice idea to me. In practice I'm not sure it would be useful for me because I already ignore all GitHub notifications (I'm simply getting too many of them).

So, what would be the idea? If there is only 1 reviewer, ping him/her; if there are several, randomly ping one of them?

**Comment by lyrixx** [comment]
No, the idea is:

If it's workflow => me
if it's serializer => kevin
...

Globally, asign the PR to the maintainer 

We should not rely on the github guess

**Comment by lyrixx** [comment]
(off topic)
About email from github, I use the following config for many year and I really happy with it:
![screenshot12](https://cloud.githubusercontent.com/assets/408368/25234349/164785a4-25e2-11e7-99ad-51facf671fe3.png)

I got only few mail per days..

**Comment by Simperfit** [comment]
That could be a great feature :p

**Comment by javiereguiluz** [comment]
I'll try that. Thanks!

---

About the notifications, my guess is that GitHub uses some adaptive machine learning to decide the best reviewers. Would that be better than a static map? (this would avoid problems like pinging a person long after he/she abandoned the project ... for example: forms should not ping Bernhard but Jules).

**Comment by HeahDude** [comment]
@javiereguiluz AFAIK GitHub uses the last persons who reviewed or modified files that change in the proposed PR.

**Comment by lyrixx** [comment]
That why I said I would be opt-in ;)

**Comment by stof** [comment]
@javiereguiluz you can also filter the PR list to see only the ones on which you were requested a review (if you write the filter manually rather than using predefined filters, you can also see PRs with review requested for someone else, but this is less useful)

**Comment by dxops** [comment]
It looks like CODEOWNERS Github feature, right? https://blog.github.com/2017-07-06-introducing-code-owners/

**Comment by lyrixx** [comment]
Indeed thanks. I will look at it ;)

**Comment by lyrixx** [comment]
refs https://github.com/symfony/symfony/pull/27079 . Will see if it works well ;)

**Comment by lyrixx** [comment]
I works well. We can close this issue.
