### ISSUE TITLE
"Missing tests" labels

### ISSUE THREAD

**Issue by sroze** [carsonbot/carsonbot#62]
What do you think about adding a "Missing tests" label automatically added by Carsonbot?

**Comment by sstok** [comment]
This sounds like a really cool idea, but how can we make it reliable? the absence of tests in a pull request doesn't necessarily have to be a problem 🤔

**Comment by nicolas-grekas** [comment]
I think this is not applicable is practice, that's what reviews are for, let's close :)

**Comment by sroze** [comment]
Fair enough :)
