### ISSUE TITLE
Add state "Ready for Merge"

### ISSUE THREAD

**Issue by webmozart** [carsonbot/carsonbot#7]
The status "Ready for Merge" should be set automatically once a PR has received two `:+1:` by different deciders and no `:-1:`. See the [Pull Request Voting Policy](http://symfony.com/doc/current/contributing/code/core_team.html#pull-request-voting-policy) for details.

This label informs mergers that they can merge a PR.

**Comment by HeahDude** [comment]
There is already a label "ready" that could be used for a maintainers hook.
