### ISSUE TITLE
Add "Status: Needs work" when someone is commenting on a codeline

### ISSUE THREAD

**Issue by Simperfit** [carsonbot/carsonbot#71]
Today to be able to have Needs Work, someone has to request changes, but IMHO just adding comments on the PR should be it, because commenting without requesting changes is like requesting changes IMHO ;).

**Comment by xabbuh** [comment]
You can already make Carson add this label by including the "Status: Needs work" string in your comment.

**Comment by Simperfit** [comment]
Yes but what I meant in for exemple someone making comments in a PR, not applying the needs work label, If for any reason I have already seen the notification but had no time at the moment, I can forget to check that PR back and let the comment be here until I recheck all of the PRs.

**Comment by ogizanagi** [comment]
> commenting without requesting changes is like requesting changes

I don't agree with this anyway. Comments (even on a code line) could be anything, from asking code change to supportive comments, suggesting new ideas for the future or asking for more information about something in particular. Does not always mean the current state of the PR should be changed.
If the intent really is to ask for code changes, the "request changes" option should be used. Let's use the semantics and UI already provided by Github when possible, not inferring more :)

**Comment by Simperfit** [comment]
Understood ! :p
