### ISSUE TITLE
Add component labels to PRs

### ISSUE THREAD

**Issue by webmozart** [carsonbot/carsonbot#8]
When a PR is (1) submitted (2?) updated, it's modified files should be scanned and used to set the appropriate component/bridge/bundle labels for the PR.

**Comment by dosten** [comment]
What do you think about add this info into the PR template? Think about a change related to the Security Bundle and the Security component, the PR/Issue title has a limit, so, this reduce the length of the real title.

```markdown
| Q             | A
| ------------- | ---
| Components    | Security, SecurityBundle
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1234
| License       | MIT
| Doc PR        | symfony/symfony-docs#1234
```

**Comment by WouterJ** [comment]
-1 on making the PR table any longer.

Scanning the modified files, like @webmozart suggested, should bring enough results.

**Comment by webmozart** [comment]
I agree with @WouterJ. Scanning the files should work in most cases, and where it doesn't we can manually adjust the labels.

**Comment by lyrixx** [comment]
Could be close ?

**Comment by Nyholm** [comment]
I think this can be closed for now. 

It could be reopened if we still think this is a good idea
