### ISSUE TITLE
Fix PR title prefixes

### ISSUE THREAD

**Issue by webmozart** [carsonbot/carsonbot#9]
Once #8 is implemented, the bot should fix the title prefixes of PRs whenever their component/bundle/bridge labels are changed:
- `[<component>]` prefixes should be added for each component/bundle/bridge label
- superfluous `[xxx]` prefixes (e.g. `[WIP]`) should be removed

The idea is to retain the component labels of a PR in the Git log.

**Comment by Nyholm** [comment]
I agree with this. I'll start work on it. 

It should only prepend the title with "gray" (#dddddd) labels.

**Comment by wouterj** [comment]
Btw, Carson at the moment only parses the first prefix IIRC. It should add multiple labels when e.g. doing `[Form][Validator] ...`.

**Comment by Nyholm** [comment]
👍
